# Generated by Django 4.2.11 on 2024-04-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yourdemy", "0003_courses_about_courses_description_courses_instrs_des"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="special_offers",
            field=models.BooleanField(default=False),
        ),
    ]
