# Generated by Django 4.2.11 on 2024-04-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yourdemy", "0005_courses_image_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_chunk_option_suitable", models.BooleanField(default=True)),
                (
                    "video_length_options",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("15", "15 mins"),
                            ("20", "20 mins"),
                            ("10", "10 mins"),
                            ("25", "25 mins"),
                            ("30", "30 mins"),
                        ],
                        max_length=3,
                    ),
                ),
                ("quiz_option_suitable", models.BooleanField(default=True)),
                (
                    "quiz_options",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("15", "Quiz every 15 mins"),
                            ("20", "Quiz every 20 mins"),
                            ("10", "Quiz half way through"),
                            ("25", "Quiz at the end of the module"),
                            ("30", "Quiz at the end of the course"),
                        ],
                        max_length=3,
                    ),
                ),
                ("suggestions", models.TextField()),
            ],
        ),
    ]
