# Generated by Django 4.2.11 on 2024-04-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yourdemy", "0006_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="duration", field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="user",
            name="quiz_location",
            field=models.TextField(default="End of Section"),
        ),
    ]
