# Generated by Django 4.2.11 on 2024-04-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("yourdemy", "0007_user_duration_user_quiz_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestions",
            fields=[
                ("ques_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                (
                    "order",
                    models.IntegerField(
                        help_text="The order in which video lectures are displayed"
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="yourdemy.videolecture",
                    ),
                ),
            ],
            options={"ordering": ["order"],},
        ),
    ]
